"""add posts, meetings, deadlines, checklist_progress, user name

Revision ID: 0f0d77437741
Revises: ab507cc3d822
Create Date: 2026-07-23 00:46:30.411418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0d77437741'
down_revision: Union[str, Sequence[str], None] = 'ab507cc3d822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
