"""add must_change_password, leads table

Revision ID: 3cdc0f62c3d3
Revises: 0f705cf550bc
Create Date: 2026-08-01 01:10:11.454758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdc0f62c3d3'
down_revision: Union[str, Sequence[str], None] = '0f705cf550bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # fica assim
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    # ### end Alembic commands ###
