"""add service_type to requests

Revision ID: 66b0b5d8460c
Revises: ef56ff9dfdca
Create Date: 2026-08-10 20:35:10.733428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b0b5d8460c'
down_revision: Union[str, Sequence[str], None] = 'ef56ff9dfdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('requests', sa.Column('service_type', sa.String(length=50), nullable=False, server_default='relatorio'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'service_type')
    # ### end Alembic commands ###
