"""add posts, meetings, deadlines, checklist_progress, user.name

Revision ID: ab507cc3d822
Revises: 415d80cc6a2b
Create Date: 2026-07-22 23:25:32.325256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab507cc3d822'
down_revision: Union[str, Sequence[str], None] = '415d80cc6a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
