"""simplify request model

Revision ID: d19dcd7180e6
Revises: 36e439a5c6fb
Create Date: 2026-06-06 22:21:54.167763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd19dcd7180e6'
down_revision: Union[str, Sequence[str], None] = '36e439a5c6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'knowledge_field')
    op.drop_column('requests', 'area')
    op.drop_column('requests', 'subarea')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('subarea', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('area', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('knowledge_field', postgresql.ENUM('ciencias_agrarias', 'ciencias_biologicas', 'ciencias_da_saude', 'ciencias_exatas', 'ciencias_humanas', 'ciencias_sociais', 'engenharias', 'linguistica', 'multidisciplinar', name='knowledgefield'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
